#!/usr/bin/env bash

set -e

# Clean up.
echo "Cleaning up"
cabal clean

# Build and test.
echo "Building"
cabal build all

echo "Testing"
cabal test

CACHE_PATH=$(mktemp -d -t magix-XXXXXX)
echo "Temporary cache path is ${CACHE_PATH}"

# Sample scripts.
LANGUAGES=("bash" "haskell")
for l in "${LANGUAGES[@]}"; do
    echo "Running sample scripts for language ${l}"
    dir="test-scripts/${l}"
    cabal run magix -- --cache-path "$CACHE_PATH" -v "${dir}/minimal"
    cabal run magix -- --cache-path "$CACHE_PATH" -v "${dir}/minimal with spaces"
    cabal run magix -- --cache-path "$CACHE_PATH" -v "${dir}/args" -h and other args
done
