#!/usr/bin/env bash

set -e

# Clean up.
cabal clean
rm -rf "$XDG_CACHE_HOME/magix"

# Build and run.
cabal build all
cabal test
cabal run magix -- -v test-scripts/minimal-bash
cabal run magix -- -v test-scripts/minimal-haskell
