#!/usr/bin/env bash

set -e

# Clean up.
echo "Cleaning up"
cabal clean >/dev/null
rm -rf "$XDG_CACHE_HOME/magix/*"

# Build and test.
echo "Building"
cabal build all >/dev/null

echo "Testing"
cabal test >/dev/null

# Sample scripts.
LANGUAGES=("bash" "haskell")
for l in "${LANGUAGES[@]}"; do
    echo "Running sample scripts for language ${l}"
    dir="test-scripts/${l}"
    cabal run magix -- -v "${dir}/minimal" >/dev/null
    cabal run magix -- -v "${dir}/minimal with spaces" >/dev/null
    cabal run magix -- -v "${dir}/args" -h and other args >/dev/null
done
