#!/usr/bin/env bash

set -e

# Clean up.
echo "Cleaning up"
cabal clean
rm -rfv "$XDG_CACHE_HOME/magix/"*

# Build and test.
echo "Building"
cabal build all

echo "Testing"
cabal test

# Sample scripts.
LANGUAGES=("bash" "haskell")
for l in "${LANGUAGES[@]}"; do
    echo "Running sample scripts for language ${l}"
    dir="test-scripts/${l}"
    cabal run magix -- -v "${dir}/minimal"
    cabal run magix -- -v "${dir}/minimal with spaces"
    cabal run magix -- -v "${dir}/args" -h and other args
done
